package adris.altoclef.util.helpers;

import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;

public class BuildingBlockHelper {
    public static boolean isSolidBlock(final Item item) {
        if (!(item instanceof BlockItem)) {
            return false;
        }
        final BlockItem blockItem = (BlockItem)item;
        final Block block = blockItem.getBlock();
        return isSolidBlock(block);
    }
    public static boolean isSolidBlock(final Block block) {
        if (block.equals(Blocks.STONE) || block.equals(Blocks.GRANITE) || block.equals(Blocks.POLISHED_GRANITE) || block.equals(Blocks.DIORITE) || block.equals(Blocks.POLISHED_DIORITE) || block.equals(Blocks.ANDESITE) || block.equals(Blocks.POLISHED_ANDESITE) || block.equals(Blocks.GRASS_BLOCK) || block.equals(Blocks.DIRT) || block.equals(Blocks.COARSE_DIRT) || block.equals(Blocks.PODZOL) || block.equals(Blocks.COBBLESTONE) || block.equals(Blocks.OAK_PLANKS) || block.equals(Blocks.SPRUCE_PLANKS) || block.equals(Blocks.BIRCH_PLANKS) || block.equals(Blocks.JUNGLE_PLANKS) || block.equals(Blocks.ACACIA_PLANKS) || block.equals(Blocks.DARK_OAK_PLANKS) || block.equals(Blocks.MANGROVE_PLANKS) || block.equals(Blocks.BEDROCK) || block.equals(Blocks.SAND) || block.equals(Blocks.RED_SAND) || block.equals(Blocks.GRAVEL) || block.equals(Blocks.GOLD_ORE) || block.equals(Blocks.DEEPSLATE_GOLD_ORE) || block.equals(Blocks.IRON_ORE) || block.equals(Blocks.DEEPSLATE_IRON_ORE) || block.equals(Blocks.COAL_ORE) || block.equals(Blocks.DEEPSLATE_COAL_ORE) || block.equals(Blocks.NETHER_GOLD_ORE) || block.equals(Blocks.OAK_LOG) || block.equals(Blocks.SPRUCE_LOG) || block.equals(Blocks.BIRCH_LOG) || block.equals(Blocks.JUNGLE_LOG) || block.equals(Blocks.ACACIA_LOG) || block.equals(Blocks.DARK_OAK_LOG) || block.equals(Blocks.MANGROVE_LOG) || block.equals(Blocks.MANGROVE_ROOTS) || block.equals(Blocks.MUDDY_MANGROVE_ROOTS) || block.equals(Blocks.STRIPPED_SPRUCE_LOG) || block.equals(Blocks.STRIPPED_BIRCH_LOG) || block.equals(Blocks.STRIPPED_JUNGLE_LOG) || block.equals(Blocks.STRIPPED_ACACIA_LOG) || block.equals(Blocks.STRIPPED_DARK_OAK_LOG) || block.equals(Blocks.STRIPPED_OAK_LOG) || block.equals(Blocks.STRIPPED_MANGROVE_LOG) || block.equals(Blocks.OAK_WOOD) || block.equals(Blocks.SPRUCE_WOOD) || block.equals(Blocks.BIRCH_WOOD) || block.equals(Blocks.JUNGLE_WOOD) || block.equals(Blocks.ACACIA_WOOD) || block.equals(Blocks.DARK_OAK_WOOD) || block.equals(Blocks.MANGROVE_WOOD) || block.equals(Blocks.STRIPPED_OAK_WOOD) || block.equals(Blocks.STRIPPED_SPRUCE_WOOD) || block.equals(Blocks.STRIPPED_BIRCH_WOOD) || block.equals(Blocks.STRIPPED_JUNGLE_WOOD) || block.equals(Blocks.STRIPPED_ACACIA_WOOD) || block.equals(Blocks.STRIPPED_DARK_OAK_WOOD) || block.equals(Blocks.STRIPPED_MANGROVE_WOOD) || block.equals(Blocks.OAK_LEAVES) || block.equals(Blocks.SPRUCE_LEAVES) || block.equals(Blocks.BIRCH_LEAVES) || block.equals(Blocks.JUNGLE_LEAVES) || block.equals(Blocks.ACACIA_LEAVES) || block.equals(Blocks.DARK_OAK_LEAVES) || block.equals(Blocks.MANGROVE_LEAVES) || block.equals(Blocks.AZALEA_LEAVES) || block.equals(Blocks.SPONGE) || block.equals(Blocks.WET_SPONGE) || block.equals(Blocks.GLASS) || block.equals(Blocks.LAPIS_ORE) || block.equals(Blocks.DEEPSLATE_LAPIS_ORE) || block.equals(Blocks.LAPIS_BLOCK) || block.equals(Blocks.DISPENSER) || block.equals(Blocks.SANDSTONE) || block.equals(Blocks.CHISELED_SANDSTONE) || block.equals(Blocks.CUT_SANDSTONE) || block.equals(Blocks.NOTE_BLOCK) || block.equals(Blocks.STICKY_PISTON) || block.equals(Blocks.PISTON) || block.equals(Blocks.WHITE_WOOL) || block.equals(Blocks.ORANGE_WOOL) || block.equals(Blocks.MAGENTA_WOOL) || block.equals(Blocks.LIGHT_BLUE_WOOL) || block.equals(Blocks.YELLOW_WOOL) || block.equals(Blocks.LIME_WOOL) || block.equals(Blocks.PINK_WOOL) || block.equals(Blocks.GRAY_WOOL) || block.equals(Blocks.LIGHT_GRAY_WOOL) || block.equals(Blocks.CYAN_WOOL) || block.equals(Blocks.PURPLE_WOOL) || block.equals(Blocks.BLUE_WOOL) || block.equals(Blocks.BROWN_WOOL) || block.equals(Blocks.GREEN_WOOL) || block.equals(Blocks.RED_WOOL) || block.equals(Blocks.BLACK_WOOL) || block.equals(Blocks.MOVING_PISTON) || block.equals(Blocks.GOLD_BLOCK) || block.equals(Blocks.IRON_BLOCK) || block.equals(Blocks.BRICKS) || block.equals(Blocks.TNT) || block.equals(Blocks.BOOKSHELF) || block.equals(Blocks.MOSSY_COBBLESTONE) || block.equals(Blocks.OBSIDIAN) || block.equals(Blocks.WALL_TORCH) || block.equals(Blocks.SPAWNER) || block.equals(Blocks.CHEST) || block.equals(Blocks.DIAMOND_ORE) || block.equals(Blocks.DEEPSLATE_DIAMOND_ORE) || block.equals(Blocks.DIAMOND_BLOCK) || block.equals(Blocks.CRAFTING_TABLE) || block.equals(Blocks.FARMLAND) || block.equals(Blocks.FURNACE) || block.equals(Blocks.REDSTONE_ORE) || block.equals(Blocks.DEEPSLATE_REDSTONE_ORE) || block.equals(Blocks.ICE) || block.equals(Blocks.SNOW_BLOCK) || block.equals(Blocks.JUKEBOX) || block.equals(Blocks.PUMPKIN) || block.equals(Blocks.NETHERRACK) || block.equals(Blocks.SOUL_SAND) || block.equals(Blocks.SOUL_SOIL) || block.equals(Blocks.BASALT) || block.equals(Blocks.POLISHED_BASALT) || block.equals(Blocks.GLOWSTONE) || block.equals(Blocks.NETHER_PORTAL) || block.equals(Blocks.CARVED_PUMPKIN) || block.equals(Blocks.JACK_O_LANTERN) || block.equals(Blocks.WHITE_STAINED_GLASS) || block.equals(Blocks.ORANGE_STAINED_GLASS) || block.equals(Blocks.MAGENTA_STAINED_GLASS) || block.equals(Blocks.LIGHT_BLUE_STAINED_GLASS) || block.equals(Blocks.YELLOW_STAINED_GLASS) || block.equals(Blocks.LIME_STAINED_GLASS) || block.equals(Blocks.PINK_STAINED_GLASS) || block.equals(Blocks.GRAY_STAINED_GLASS) || block.equals(Blocks.LIGHT_GRAY_STAINED_GLASS) || block.equals(Blocks.CYAN_STAINED_GLASS) || block.equals(Blocks.PURPLE_STAINED_GLASS) || block.equals(Blocks.BLUE_STAINED_GLASS) || block.equals(Blocks.BROWN_STAINED_GLASS) || block.equals(Blocks.GREEN_STAINED_GLASS) || block.equals(Blocks.RED_STAINED_GLASS) || block.equals(Blocks.BLACK_STAINED_GLASS) || block.equals(Blocks.STONE_BRICKS) || block.equals(Blocks.MOSSY_STONE_BRICKS) || block.equals(Blocks.CRACKED_STONE_BRICKS) || block.equals(Blocks.CHISELED_STONE_BRICKS) || block.equals(Blocks.PACKED_MUD) || block.equals(Blocks.MUD_BRICKS) || block.equals(Blocks.INFESTED_STONE) || block.equals(Blocks.INFESTED_COBBLESTONE) || block.equals(Blocks.INFESTED_STONE_BRICKS) || block.equals(Blocks.INFESTED_MOSSY_STONE_BRICKS) || block.equals(Blocks.INFESTED_CRACKED_STONE_BRICKS) || block.equals(Blocks.INFESTED_CHISELED_STONE_BRICKS) || block.equals(Blocks.BROWN_MUSHROOM_BLOCK) || block.equals(Blocks.RED_MUSHROOM_BLOCK) || block.equals(Blocks.MUSHROOM_STEM) || block.equals(Blocks.MELON) || block.equals(Blocks.MYCELIUM) || block.equals(Blocks.NETHER_BRICKS) || block.equals(Blocks.ENCHANTING_TABLE) || block.equals(Blocks.BREWING_STAND) || block.equals(Blocks.CAULDRON) || block.equals(Blocks.END_PORTAL_FRAME) || block.equals(Blocks.END_STONE) || block.equals(Blocks.REDSTONE_LAMP) || block.equals(Blocks.SANDSTONE_STAIRS) || block.equals(Blocks.EMERALD_ORE) || block.equals(Blocks.DEEPSLATE_EMERALD_ORE) || block.equals(Blocks.ENDER_CHEST) || block.equals(Blocks.TRIPWIRE_HOOK) || block.equals(Blocks.TRIPWIRE) || block.equals(Blocks.EMERALD_BLOCK) || block.equals(Blocks.SPRUCE_STAIRS) || block.equals(Blocks.BIRCH_STAIRS) || block.equals(Blocks.JUNGLE_STAIRS) || block.equals(Blocks.COMMAND_BLOCK) || block.equals(Blocks.BEACON) || block.equals(Blocks.COBBLESTONE_WALL) || block.equals(Blocks.MOSSY_COBBLESTONE_WALL) || block.equals(Blocks.SKELETON_SKULL) || block.equals(Blocks.SKELETON_WALL_SKULL) || block.equals(Blocks.WITHER_SKELETON_SKULL) || block.equals(Blocks.WITHER_SKELETON_WALL_SKULL) || block.equals(Blocks.ZOMBIE_HEAD) || block.equals(Blocks.ZOMBIE_WALL_HEAD) || block.equals(Blocks.PLAYER_HEAD) || block.equals(Blocks.PLAYER_WALL_HEAD) || block.equals(Blocks.CREEPER_HEAD) || block.equals(Blocks.CREEPER_WALL_HEAD) || block.equals(Blocks.DRAGON_HEAD) || block.equals(Blocks.DRAGON_WALL_HEAD) || block.equals(Blocks.CHIPPED_ANVIL) || block.equals(Blocks.DAMAGED_ANVIL) || block.equals(Blocks.TRAPPED_CHEST) || block.equals(Blocks.COMPARATOR) || block.equals(Blocks.DAYLIGHT_DETECTOR) || block.equals(Blocks.REDSTONE_BLOCK) || block.equals(Blocks.NETHER_QUARTZ_ORE) || block.equals(Blocks.HOPPER) || block.equals(Blocks.QUARTZ_BLOCK) || block.equals(Blocks.CHISELED_QUARTZ_BLOCK) || block.equals(Blocks.QUARTZ_PILLAR) || block.equals(Blocks.QUARTZ_STAIRS) || block.equals(Blocks.ACTIVATOR_RAIL) || block.equals(Blocks.DROPPER) || block.equals(Blocks.WHITE_TERRACOTTA) || block.equals(Blocks.ORANGE_TERRACOTTA) || block.equals(Blocks.MAGENTA_TERRACOTTA) || block.equals(Blocks.LIGHT_BLUE_TERRACOTTA) || block.equals(Blocks.YELLOW_TERRACOTTA) || block.equals(Blocks.LIME_TERRACOTTA) || block.equals(Blocks.PINK_TERRACOTTA) || block.equals(Blocks.GRAY_TERRACOTTA) || block.equals(Blocks.LIGHT_GRAY_TERRACOTTA) || block.equals(Blocks.CYAN_TERRACOTTA) || block.equals(Blocks.PURPLE_TERRACOTTA) || block.equals(Blocks.BLUE_TERRACOTTA) || block.equals(Blocks.BROWN_TERRACOTTA) || block.equals(Blocks.GREEN_TERRACOTTA) || block.equals(Blocks.RED_TERRACOTTA) || block.equals(Blocks.BLACK_TERRACOTTA) || block.equals(Blocks.ACACIA_STAIRS) || block.equals(Blocks.DARK_OAK_STAIRS) || block.equals(Blocks.MANGROVE_STAIRS) || block.equals(Blocks.SLIME_BLOCK) || block.equals(Blocks.BARRIER) || block.equals(Blocks.PRISMARINE) || block.equals(Blocks.PRISMARINE_BRICKS) || block.equals(Blocks.DARK_PRISMARINE) || block.equals(Blocks.PRISMARINE_STAIRS) || block.equals(Blocks.PRISMARINE_BRICK_STAIRS) || block.equals(Blocks.DARK_PRISMARINE_STAIRS) || block.equals(Blocks.SEA_LANTERN) || block.equals(Blocks.HAY_BLOCK) || block.equals(Blocks.TERRACOTTA) || block.equals(Blocks.COAL_BLOCK) || block.equals(Blocks.PACKED_ICE) || block.equals(Blocks.RED_SANDSTONE) || block.equals(Blocks.CHISELED_RED_SANDSTONE) || block.equals(Blocks.CUT_RED_SANDSTONE) || block.equals(Blocks.RED_SANDSTONE_STAIRS) || block.equals(Blocks.SMOOTH_STONE) || block.equals(Blocks.SMOOTH_SANDSTONE) || block.equals(Blocks.SMOOTH_QUARTZ) || block.equals(Blocks.SMOOTH_RED_SANDSTONE) || block.equals(Blocks.END_ROD) || block.equals(Blocks.CHORUS_FLOWER) || block.equals(Blocks.PURPUR_BLOCK) || block.equals(Blocks.PURPUR_PILLAR) || block.equals(Blocks.PURPUR_STAIRS) || block.equals(Blocks.END_STONE_BRICKS) || block.equals(Blocks.BEETROOTS) || block.equals(Blocks.DIRT_PATH) || block.equals(Blocks.END_GATEWAY) || block.equals(Blocks.REPEATING_COMMAND_BLOCK) || block.equals(Blocks.CHAIN_COMMAND_BLOCK) || block.equals(Blocks.FROSTED_ICE) || block.equals(Blocks.MAGMA_BLOCK) || block.equals(Blocks.NETHER_WART_BLOCK) || block.equals(Blocks.RED_NETHER_BRICKS) || block.equals(Blocks.BONE_BLOCK) || block.equals(Blocks.STRUCTURE_VOID) || block.equals(Blocks.OBSERVER) || block.equals(Blocks.SHULKER_BOX) || block.equals(Blocks.WHITE_SHULKER_BOX) || block.equals(Blocks.ORANGE_SHULKER_BOX) || block.equals(Blocks.MAGENTA_SHULKER_BOX) || block.equals(Blocks.LIGHT_BLUE_SHULKER_BOX) || block.equals(Blocks.YELLOW_SHULKER_BOX) || block.equals(Blocks.LIME_SHULKER_BOX) || block.equals(Blocks.PINK_SHULKER_BOX) || block.equals(Blocks.GRAY_SHULKER_BOX) || block.equals(Blocks.LIGHT_GRAY_SHULKER_BOX) || block.equals(Blocks.CYAN_SHULKER_BOX) || block.equals(Blocks.PURPLE_SHULKER_BOX) || block.equals(Blocks.BLUE_SHULKER_BOX) || block.equals(Blocks.BROWN_SHULKER_BOX) || block.equals(Blocks.GREEN_SHULKER_BOX) || block.equals(Blocks.RED_SHULKER_BOX) || block.equals(Blocks.BLACK_SHULKER_BOX) || block.equals(Blocks.WHITE_GLAZED_TERRACOTTA) || block.equals(Blocks.ORANGE_GLAZED_TERRACOTTA) || block.equals(Blocks.MAGENTA_GLAZED_TERRACOTTA) || block.equals(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA) || block.equals(Blocks.YELLOW_GLAZED_TERRACOTTA) || block.equals(Blocks.LIME_GLAZED_TERRACOTTA) || block.equals(Blocks.PINK_GLAZED_TERRACOTTA) || block.equals(Blocks.GRAY_GLAZED_TERRACOTTA) || block.equals(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA) || block.equals(Blocks.CYAN_GLAZED_TERRACOTTA) || block.equals(Blocks.PURPLE_GLAZED_TERRACOTTA) || block.equals(Blocks.BLUE_GLAZED_TERRACOTTA) || block.equals(Blocks.BROWN_GLAZED_TERRACOTTA) || block.equals(Blocks.GREEN_GLAZED_TERRACOTTA) || block.equals(Blocks.RED_GLAZED_TERRACOTTA) || block.equals(Blocks.BLACK_GLAZED_TERRACOTTA) || block.equals(Blocks.WHITE_CONCRETE) || block.equals(Blocks.ORANGE_CONCRETE) || block.equals(Blocks.MAGENTA_CONCRETE) || block.equals(Blocks.LIGHT_BLUE_CONCRETE) || block.equals(Blocks.YELLOW_CONCRETE) || block.equals(Blocks.LIME_CONCRETE) || block.equals(Blocks.PINK_CONCRETE) || block.equals(Blocks.GRAY_CONCRETE) || block.equals(Blocks.LIGHT_GRAY_CONCRETE) || block.equals(Blocks.CYAN_CONCRETE) || block.equals(Blocks.PURPLE_CONCRETE) || block.equals(Blocks.BLUE_CONCRETE) || block.equals(Blocks.BROWN_CONCRETE) || block.equals(Blocks.GREEN_CONCRETE) || block.equals(Blocks.RED_CONCRETE) || block.equals(Blocks.BLACK_CONCRETE) || block.equals(Blocks.DRIED_KELP_BLOCK) || block.equals(Blocks.DEAD_TUBE_CORAL_BLOCK) || block.equals(Blocks.DEAD_BRAIN_CORAL_BLOCK) || block.equals(Blocks.DEAD_BUBBLE_CORAL_BLOCK) || block.equals(Blocks.DEAD_FIRE_CORAL_BLOCK) || block.equals(Blocks.DEAD_HORN_CORAL_BLOCK) || block.equals(Blocks.TUBE_CORAL_BLOCK) || block.equals(Blocks.BRAIN_CORAL_BLOCK) || block.equals(Blocks.BUBBLE_CORAL_BLOCK) || block.equals(Blocks.FIRE_CORAL_BLOCK) || block.equals(Blocks.HORN_CORAL_BLOCK) || block.equals(Blocks.BLUE_ICE) || block.equals(Blocks.CONDUIT) || block.equals(Blocks.BUBBLE_COLUMN) || block.equals(Blocks.POLISHED_GRANITE_STAIRS) || block.equals(Blocks.SMOOTH_RED_SANDSTONE_STAIRS) || block.equals(Blocks.MOSSY_STONE_BRICK_STAIRS) || block.equals(Blocks.POLISHED_DIORITE_STAIRS) || block.equals(Blocks.MOSSY_COBBLESTONE_STAIRS) || block.equals(Blocks.END_STONE_BRICK_STAIRS) || block.equals(Blocks.STONE_STAIRS) || block.equals(Blocks.SMOOTH_SANDSTONE_STAIRS) || block.equals(Blocks.SMOOTH_QUARTZ_STAIRS) || block.equals(Blocks.GRANITE_STAIRS) || block.equals(Blocks.ANDESITE_STAIRS) || block.equals(Blocks.RED_NETHER_BRICK_STAIRS) || block.equals(Blocks.POLISHED_ANDESITE_STAIRS) || block.equals(Blocks.DIORITE_STAIRS) || block.equals(Blocks.BRICK_WALL) || block.equals(Blocks.PRISMARINE_WALL) || block.equals(Blocks.RED_SANDSTONE_WALL) || block.equals(Blocks.MOSSY_STONE_BRICK_WALL) || block.equals(Blocks.GRANITE_WALL) || block.equals(Blocks.STONE_BRICK_WALL) || block.equals(Blocks.MUD_BRICK_WALL) || block.equals(Blocks.NETHER_BRICK_WALL) || block.equals(Blocks.ANDESITE_WALL) || block.equals(Blocks.RED_NETHER_BRICK_WALL) || block.equals(Blocks.SANDSTONE_WALL) || block.equals(Blocks.END_STONE_BRICK_WALL) || block.equals(Blocks.DIORITE_WALL) || block.equals(Blocks.SCAFFOLDING) || block.equals(Blocks.LOOM) || block.equals(Blocks.BARREL) || block.equals(Blocks.SMOKER) || block.equals(Blocks.BLAST_FURNACE) || block.equals(Blocks.CARTOGRAPHY_TABLE) || block.equals(Blocks.FLETCHING_TABLE) || block.equals(Blocks.GRINDSTONE) || block.equals(Blocks.LECTERN) || block.equals(Blocks.SMITHING_TABLE) || block.equals(Blocks.STONECUTTER) || block.equals(Blocks.BELL) || block.equals(Blocks.LANTERN) || block.equals(Blocks.SOUL_LANTERN) || block.equals(Blocks.CAMPFIRE) || block.equals(Blocks.SOUL_CAMPFIRE) || block.equals(Blocks.WARPED_STEM) || block.equals(Blocks.STRIPPED_WARPED_STEM) || block.equals(Blocks.WARPED_HYPHAE) || block.equals(Blocks.STRIPPED_WARPED_HYPHAE) || block.equals(Blocks.WARPED_NYLIUM) || block.equals(Blocks.WARPED_FUNGUS) || block.equals(Blocks.WARPED_WART_BLOCK) || block.equals(Blocks.WARPED_ROOTS) || block.equals(Blocks.NETHER_SPROUTS) || block.equals(Blocks.CRIMSON_STEM) || block.equals(Blocks.STRIPPED_CRIMSON_STEM) || block.equals(Blocks.CRIMSON_HYPHAE) || block.equals(Blocks.STRIPPED_CRIMSON_HYPHAE) || block.equals(Blocks.CRIMSON_NYLIUM) || block.equals(Blocks.CRIMSON_FUNGUS) || block.equals(Blocks.SHROOMLIGHT) || block.equals(Blocks.CRIMSON_ROOTS) || block.equals(Blocks.CRIMSON_PLANKS) || block.equals(Blocks.WARPED_PLANKS) || block.equals(Blocks.CRIMSON_STAIRS) || block.equals(Blocks.WARPED_STAIRS) || block.equals(Blocks.CRIMSON_BUTTON) || block.equals(Blocks.WARPED_BUTTON) || block.equals(Blocks.STRUCTURE_BLOCK) || block.equals(Blocks.JIGSAW) || block.equals(Blocks.COMPOSTER) || block.equals(Blocks.TARGET) || block.equals(Blocks.BEE_NEST) || block.equals(Blocks.BEEHIVE) || block.equals(Blocks.HONEY_BLOCK) || block.equals(Blocks.HONEYCOMB_BLOCK) || block.equals(Blocks.NETHERITE_BLOCK) || block.equals(Blocks.ANCIENT_DEBRIS) || block.equals(Blocks.CRYING_OBSIDIAN) || block.equals(Blocks.RESPAWN_ANCHOR) || block.equals(Blocks.LODESTONE) || block.equals(Blocks.BLACKSTONE) || block.equals(Blocks.BLACKSTONE_STAIRS) || block.equals(Blocks.BLACKSTONE_WALL) || block.equals(Blocks.POLISHED_BLACKSTONE) || block.equals(Blocks.POLISHED_BLACKSTONE_BRICKS) || block.equals(Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS) || block.equals(Blocks.CHISELED_POLISHED_BLACKSTONE) || block.equals(Blocks.POLISHED_BLACKSTONE_BRICK_STAIRS) || block.equals(Blocks.POLISHED_BLACKSTONE_BRICK_WALL) || block.equals(Blocks.GILDED_BLACKSTONE) || block.equals(Blocks.POLISHED_BLACKSTONE_STAIRS) || block.equals(Blocks.POLISHED_BLACKSTONE_BUTTON) || block.equals(Blocks.POLISHED_BLACKSTONE_WALL) || block.equals(Blocks.CHISELED_NETHER_BRICKS) || block.equals(Blocks.CRACKED_NETHER_BRICKS) || block.equals(Blocks.QUARTZ_BRICKS) || block.equals(Blocks.AMETHYST_BLOCK) || block.equals(Blocks.BUDDING_AMETHYST) || block.equals(Blocks.AMETHYST_CLUSTER) || block.equals(Blocks.LARGE_AMETHYST_BUD) || block.equals(Blocks.MEDIUM_AMETHYST_BUD) || block.equals(Blocks.SMALL_AMETHYST_BUD) || block.equals(Blocks.TUFF) || block.equals(Blocks.CALCITE) || block.equals(Blocks.TINTED_GLASS) || block.equals(Blocks.POWDER_SNOW) || block.equals(Blocks.SCULK_SENSOR) || block.equals(Blocks.SCULK) || block.equals(Blocks.SCULK_VEIN) || block.equals(Blocks.SCULK_CATALYST) || block.equals(Blocks.SCULK_SHRIEKER) || block.equals(Blocks.OXIDIZED_COPPER) || block.equals(Blocks.WEATHERED_COPPER) || block.equals(Blocks.EXPOSED_COPPER) || block.equals(Blocks.COPPER_BLOCK) || block.equals(Blocks.COPPER_ORE) || block.equals(Blocks.DEEPSLATE_COPPER_ORE) || block.equals(Blocks.OXIDIZED_CUT_COPPER) || block.equals(Blocks.WEATHERED_CUT_COPPER) || block.equals(Blocks.EXPOSED_CUT_COPPER) || block.equals(Blocks.CUT_COPPER) || block.equals(Blocks.OXIDIZED_CUT_COPPER_STAIRS) || block.equals(Blocks.WEATHERED_CUT_COPPER_STAIRS) || block.equals(Blocks.EXPOSED_CUT_COPPER_STAIRS) || block.equals(Blocks.CUT_COPPER_STAIRS) || block.equals(Blocks.WAXED_COPPER_BLOCK) || block.equals(Blocks.WAXED_WEATHERED_COPPER) || block.equals(Blocks.WAXED_EXPOSED_COPPER) || block.equals(Blocks.WAXED_OXIDIZED_COPPER) || block.equals(Blocks.WAXED_OXIDIZED_CUT_COPPER) || block.equals(Blocks.WAXED_WEATHERED_CUT_COPPER) || block.equals(Blocks.WAXED_EXPOSED_CUT_COPPER) || block.equals(Blocks.WAXED_CUT_COPPER) || block.equals(Blocks.WAXED_OXIDIZED_CUT_COPPER_STAIRS) || block.equals(Blocks.WAXED_WEATHERED_CUT_COPPER_STAIRS) || block.equals(Blocks.WAXED_EXPOSED_CUT_COPPER_STAIRS) || block.equals(Blocks.WAXED_CUT_COPPER_STAIRS) || block.equals(Blocks.SPORE_BLOSSOM) || block.equals(Blocks.AZALEA) || block.equals(Blocks.FLOWERING_AZALEA) || block.equals(Blocks.MOSS_BLOCK) || block.equals(Blocks.BIG_DRIPLEAF) || block.equals(Blocks.BIG_DRIPLEAF_STEM) || block.equals(Blocks.SMALL_DRIPLEAF) || block.equals(Blocks.HANGING_ROOTS) || block.equals(Blocks.ROOTED_DIRT) || block.equals(Blocks.MUD) || block.equals(Blocks.DEEPSLATE) || block.equals(Blocks.COBBLED_DEEPSLATE) || block.equals(Blocks.COBBLED_DEEPSLATE_STAIRS) || block.equals(Blocks.COBBLED_DEEPSLATE_WALL) || block.equals(Blocks.POLISHED_DEEPSLATE) || block.equals(Blocks.POLISHED_DEEPSLATE_STAIRS) || block.equals(Blocks.POLISHED_DEEPSLATE_WALL) || block.equals(Blocks.DEEPSLATE_TILES) || block.equals(Blocks.DEEPSLATE_TILE_STAIRS) || block.equals(Blocks.DEEPSLATE_TILE_WALL) || block.equals(Blocks.DEEPSLATE_BRICKS) || block.equals(Blocks.DEEPSLATE_BRICK_STAIRS) || block.equals(Blocks.DEEPSLATE_BRICK_WALL) || block.equals(Blocks.CHISELED_DEEPSLATE) || block.equals(Blocks.CRACKED_DEEPSLATE_BRICKS) || block.equals(Blocks.CRACKED_DEEPSLATE_TILES) || block.equals(Blocks.INFESTED_DEEPSLATE) || block.equals(Blocks.SMOOTH_BASALT) || block.equals(Blocks.RAW_IRON_BLOCK) || block.equals(Blocks.RAW_COPPER_BLOCK) || block.equals(Blocks.RAW_GOLD_BLOCK) || block.equals(Blocks.OCHRE_FROGLIGHT) || block.equals(Blocks.VERDANT_FROGLIGHT) || block.equals(Blocks.PEARLESCENT_FROGLIGHT) || block.equals(Blocks.FROGSPAWN) || block.equals(Blocks.REINFORCED_DEEPSLATE)) {
            return true;
        }
        return false;

    }
}
/*
 public static boolean isSolidBlock(final Block block) {
        switch (block) {
            case Blocks.STONE:
            case Blocks.GRANITE:
            case Blocks.POLISHED_GRANITE:
            case Blocks.DIORITE:
            case Blocks.POLISHED_DIORITE:
            case Blocks.ANDESITE:
            case Blocks.POLISHED_ANDESITE:
            case Blocks.GRASS_BLOCK:
            case Blocks.DIRT:
            case Blocks.COARSE_DIRT:
            case Blocks.PODZOL:
            case Blocks.COBBLESTONE:
            case Blocks.OAK_PLANKS:
            case Blocks.SPRUCE_PLANKS:
            case Blocks.BIRCH_PLANKS:
            case Blocks.JUNGLE_PLANKS:
            case Blocks.ACACIA_PLANKS:
            case Blocks.DARK_OAK_PLANKS:
            case Blocks.MANGROVE_PLANKS:
            case Blocks.BEDROCK:
            case Blocks.SAND:
            case Blocks.RED_SAND:
            case Blocks.GRAVEL:
            case Blocks.GOLD_ORE:
            case Blocks.DEEPSLATE_GOLD_ORE:
            case Blocks.IRON_ORE:
            case Blocks.DEEPSLATE_IRON_ORE:
            case Blocks.COAL_ORE:
            case Blocks.DEEPSLATE_COAL_ORE:
            case Blocks.NETHER_GOLD_ORE:
            case Blocks.OAK_LOG:
            case Blocks.SPRUCE_LOG:
            case Blocks.BIRCH_LOG:
            case Blocks.JUNGLE_LOG:
            case Blocks.ACACIA_LOG:
            case Blocks.DARK_OAK_LOG:
            case Blocks.MANGROVE_LOG:
            case Blocks.MANGROVE_ROOTS:
            case Blocks.MUDDY_MANGROVE_ROOTS:
            case Blocks.STRIPPED_SPRUCE_LOG:
            case Blocks.STRIPPED_BIRCH_LOG:
            case Blocks.STRIPPED_JUNGLE_LOG:
            case Blocks.STRIPPED_ACACIA_LOG:
            case Blocks.STRIPPED_DARK_OAK_LOG:
            case Blocks.STRIPPED_OAK_LOG:
            case Blocks.STRIPPED_MANGROVE_LOG:
            case Blocks.OAK_WOOD:
            case Blocks.SPRUCE_WOOD:
            case Blocks.BIRCH_WOOD:
            case Blocks.JUNGLE_WOOD:
            case Blocks.ACACIA_WOOD:
            case Blocks.DARK_OAK_WOOD:
            case Blocks.MANGROVE_WOOD:
            case Blocks.STRIPPED_OAK_WOOD:
            case Blocks.STRIPPED_SPRUCE_WOOD:
            case Blocks.STRIPPED_BIRCH_WOOD:
            case Blocks.STRIPPED_JUNGLE_WOOD:
            case Blocks.STRIPPED_ACACIA_WOOD:
            case Blocks.STRIPPED_DARK_OAK_WOOD:
            case Blocks.STRIPPED_MANGROVE_WOOD:
            case Blocks.OAK_LEAVES:
            case Blocks.SPRUCE_LEAVES:
            case Blocks.BIRCH_LEAVES:
            case Blocks.JUNGLE_LEAVES:
            case Blocks.ACACIA_LEAVES:
            case Blocks.DARK_OAK_LEAVES:
            case Blocks.MANGROVE_LEAVES:
            case Blocks.AZALEA_LEAVES:
            case Blocks.SPONGE:
            case Blocks.WET_SPONGE:
            case Blocks.GLASS:
            case Blocks.LAPIS_ORE:
            case Blocks.DEEPSLATE_LAPIS_ORE:
            case Blocks.LAPIS_BLOCK:
            case Blocks.DISPENSER:
            case Blocks.SANDSTONE:
            case Blocks.CHISELED_SANDSTONE:
            case Blocks.CUT_SANDSTONE:
            case Blocks.NOTE_BLOCK:
            case Blocks.STICKY_PISTON:
            case Blocks.PISTON:
            case Blocks.WHITE_WOOL:
            case Blocks.ORANGE_WOOL:
            case Blocks.MAGENTA_WOOL:
            case Blocks.LIGHT_BLUE_WOOL:
            case Blocks.YELLOW_WOOL:
            case Blocks.LIME_WOOL:
            case Blocks.PINK_WOOL:
            case Blocks.GRAY_WOOL:
            case Blocks.LIGHT_GRAY_WOOL:
            case Blocks.CYAN_WOOL:
            case Blocks.PURPLE_WOOL:
            case Blocks.BLUE_WOOL:
            case Blocks.BROWN_WOOL:
            case Blocks.GREEN_WOOL:
            case Blocks.RED_WOOL:
            case Blocks.BLACK_WOOL:
            case Blocks.MOVING_PISTON:
            case Blocks.GOLD_BLOCK:
            case Blocks.IRON_BLOCK:
            case Blocks.BRICKS:
            case Blocks.TNT:
            case Blocks.BOOKSHELF:
            case Blocks.MOSSY_COBBLESTONE:
            case Blocks.OBSIDIAN:
            case Blocks.WALL_TORCH:
            case Blocks.SPAWNER:
            case Blocks.CHEST:
            case Blocks.DIAMOND_ORE:
            case Blocks.DEEPSLATE_DIAMOND_ORE:
            case Blocks.DIAMOND_BLOCK:
            case Blocks.CRAFTING_TABLE:
            case Blocks.FARMLAND:
            case Blocks.FURNACE:
            case Blocks.REDSTONE_ORE:
            case Blocks.DEEPSLATE_REDSTONE_ORE:
            case Blocks.ICE:
            case Blocks.SNOW_BLOCK:
            case Blocks.JUKEBOX:
            case Blocks.PUMPKIN:
            case Blocks.NETHERRACK:
            case Blocks.SOUL_SAND:
            case Blocks.SOUL_SOIL:
            case Blocks.BASALT:
            case Blocks.POLISHED_BASALT:
            case Blocks.GLOWSTONE:
            case Blocks.NETHER_PORTAL:
            case Blocks.CARVED_PUMPKIN:
            case Blocks.JACK_O_LANTERN:
            case Blocks.WHITE_STAINED_GLASS:
            case Blocks.ORANGE_STAINED_GLASS:
            case Blocks.MAGENTA_STAINED_GLASS:
            case Blocks.LIGHT_BLUE_STAINED_GLASS:
            case Blocks.YELLOW_STAINED_GLASS:
            case Blocks.LIME_STAINED_GLASS:
            case Blocks.PINK_STAINED_GLASS:
            case Blocks.GRAY_STAINED_GLASS:
            case Blocks.LIGHT_GRAY_STAINED_GLASS:
            case Blocks.CYAN_STAINED_GLASS:
            case Blocks.PURPLE_STAINED_GLASS:
            case Blocks.BLUE_STAINED_GLASS:
            case Blocks.BROWN_STAINED_GLASS:
            case Blocks.GREEN_STAINED_GLASS:
            case Blocks.RED_STAINED_GLASS:
            case Blocks.BLACK_STAINED_GLASS:
            case Blocks.STONE_BRICKS:
            case Blocks.MOSSY_STONE_BRICKS:
            case Blocks.CRACKED_STONE_BRICKS:
            case Blocks.CHISELED_STONE_BRICKS:
            case Blocks.PACKED_MUD:
            case Blocks.MUD_BRICKS:
            case Blocks.INFESTED_STONE:
            case Blocks.INFESTED_COBBLESTONE:
            case Blocks.INFESTED_STONE_BRICKS:
            case Blocks.INFESTED_MOSSY_STONE_BRICKS:
            case Blocks.INFESTED_CRACKED_STONE_BRICKS:
            case Blocks.INFESTED_CHISELED_STONE_BRICKS:
            case Blocks.BROWN_MUSHROOM_BLOCK:
            case Blocks.RED_MUSHROOM_BLOCK:
            case Blocks.MUSHROOM_STEM:
            case Blocks.MELON:
            case Blocks.MYCELIUM:
            case Blocks.NETHER_BRICKS:
            case Blocks.ENCHANTING_TABLE:
            case Blocks.BREWING_STAND:
            case Blocks.CAULDRON:
            case Blocks.END_PORTAL_FRAME:
            case Blocks.END_STONE:
            case Blocks.REDSTONE_LAMP:
            case Blocks.SANDSTONE_STAIRS:
            case Blocks.EMERALD_ORE:
            case Blocks.DEEPSLATE_EMERALD_ORE:
            case Blocks.ENDER_CHEST:
            case Blocks.TRIPWIRE_HOOK:
            case Blocks.TRIPWIRE:
            case Blocks.EMERALD_BLOCK:
            case Blocks.SPRUCE_STAIRS:
            case Blocks.BIRCH_STAIRS:
            case Blocks.JUNGLE_STAIRS:
            case Blocks.COMMAND_BLOCK:
            case Blocks.BEACON:
            case Blocks.COBBLESTONE_WALL:
            case Blocks.MOSSY_COBBLESTONE_WALL:
            case Blocks.SKELETON_SKULL:
            case Blocks.SKELETON_WALL_SKULL:
            case Blocks.WITHER_SKELETON_SKULL:
            case Blocks.WITHER_SKELETON_WALL_SKULL:
            case Blocks.ZOMBIE_HEAD:
            case Blocks.ZOMBIE_WALL_HEAD:
            case Blocks.PLAYER_HEAD:
            case Blocks.PLAYER_WALL_HEAD:
            case Blocks.CREEPER_HEAD:
            case Blocks.CREEPER_WALL_HEAD:
            case Blocks.DRAGON_HEAD:
            case Blocks.DRAGON_WALL_HEAD:
            case Blocks.CHIPPED_ANVIL:
            case Blocks.DAMAGED_ANVIL:
            case Blocks.TRAPPED_CHEST:
            case Blocks.COMPARATOR:
            case Blocks.DAYLIGHT_DETECTOR:
            case Blocks.REDSTONE_BLOCK:
            case Blocks.NETHER_QUARTZ_ORE:
            case Blocks.HOPPER:
            case Blocks.QUARTZ_BLOCK:
            case Blocks.CHISELED_QUARTZ_BLOCK:
            case Blocks.QUARTZ_PILLAR:
            case Blocks.QUARTZ_STAIRS:
            case Blocks.ACTIVATOR_RAIL:
            case Blocks.DROPPER:
            case Blocks.WHITE_TERRACOTTA:
            case Blocks.ORANGE_TERRACOTTA:
            case Blocks.MAGENTA_TERRACOTTA:
            case Blocks.LIGHT_BLUE_TERRACOTTA:
            case Blocks.YELLOW_TERRACOTTA:
            case Blocks.LIME_TERRACOTTA:
            case Blocks.PINK_TERRACOTTA:
            case Blocks.GRAY_TERRACOTTA:
            case Blocks.LIGHT_GRAY_TERRACOTTA:
            case Blocks.CYAN_TERRACOTTA:
            case Blocks.PURPLE_TERRACOTTA:
            case Blocks.BLUE_TERRACOTTA:
            case Blocks.BROWN_TERRACOTTA:
            case Blocks.GREEN_TERRACOTTA:
            case Blocks.RED_TERRACOTTA:
            case Blocks.BLACK_TERRACOTTA:
            case Blocks.ACACIA_STAIRS:
            case Blocks.DARK_OAK_STAIRS:
            case Blocks.MANGROVE_STAIRS:
            case Blocks.SLIME_BLOCK:
            case Blocks.BARRIER:
            case Blocks.PRISMARINE:
            case Blocks.PRISMARINE_BRICKS:
            case Blocks.DARK_PRISMARINE:
            case Blocks.PRISMARINE_STAIRS:
            case Blocks.PRISMARINE_BRICK_STAIRS:
            case Blocks.DARK_PRISMARINE_STAIRS:
            case Blocks.SEA_LANTERN:
            case Blocks.HAY_BLOCK:
            case Blocks.TERRACOTTA:
            case Blocks.COAL_BLOCK:
            case Blocks.PACKED_ICE:
            case Blocks.RED_SANDSTONE:
            case Blocks.CHISELED_RED_SANDSTONE:
            case Blocks.CUT_RED_SANDSTONE:
            case Blocks.RED_SANDSTONE_STAIRS:
            case Blocks.SMOOTH_STONE:
            case Blocks.SMOOTH_SANDSTONE:
            case Blocks.SMOOTH_QUARTZ:
            case Blocks.SMOOTH_RED_SANDSTONE:
            case Blocks.END_ROD:
            case Blocks.CHORUS_FLOWER:
            case Blocks.PURPUR_BLOCK:
            case Blocks.PURPUR_PILLAR:
            case Blocks.PURPUR_STAIRS:
            case Blocks.END_STONE_BRICKS:
            case Blocks.BEETROOTS:
            case Blocks.DIRT_PATH:
            case Blocks.END_GATEWAY:
            case Blocks.REPEATING_COMMAND_BLOCK:
            case Blocks.CHAIN_COMMAND_BLOCK:
            case Blocks.FROSTED_ICE:
            case Blocks.MAGMA_BLOCK:
            case Blocks.NETHER_WART_BLOCK:
            case Blocks.RED_NETHER_BRICKS:
            case Blocks.BONE_BLOCK:
            case Blocks.STRUCTURE_VOID:
            case Blocks.OBSERVER:
            case Blocks.SHULKER_BOX:
            case Blocks.WHITE_SHULKER_BOX:
            case Blocks.ORANGE_SHULKER_BOX:
            case Blocks.MAGENTA_SHULKER_BOX:
            case Blocks.LIGHT_BLUE_SHULKER_BOX:
            case Blocks.YELLOW_SHULKER_BOX:
            case Blocks.LIME_SHULKER_BOX:
            case Blocks.PINK_SHULKER_BOX:
            case Blocks.GRAY_SHULKER_BOX:
            case Blocks.LIGHT_GRAY_SHULKER_BOX:
            case Blocks.CYAN_SHULKER_BOX:
            case Blocks.PURPLE_SHULKER_BOX:
            case Blocks.BLUE_SHULKER_BOX:
            case Blocks.BROWN_SHULKER_BOX:
            case Blocks.GREEN_SHULKER_BOX:
            case Blocks.RED_SHULKER_BOX:
            case Blocks.BLACK_SHULKER_BOX:
            case Blocks.WHITE_GLAZED_TERRACOTTA:
            case Blocks.ORANGE_GLAZED_TERRACOTTA:
            case Blocks.MAGENTA_GLAZED_TERRACOTTA:
            case Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA:
            case Blocks.YELLOW_GLAZED_TERRACOTTA:
            case Blocks.LIME_GLAZED_TERRACOTTA:
            case Blocks.PINK_GLAZED_TERRACOTTA:
            case Blocks.GRAY_GLAZED_TERRACOTTA:
            case Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA:
            case Blocks.CYAN_GLAZED_TERRACOTTA:
            case Blocks.PURPLE_GLAZED_TERRACOTTA:
            case Blocks.BLUE_GLAZED_TERRACOTTA:
            case Blocks.BROWN_GLAZED_TERRACOTTA:
            case Blocks.GREEN_GLAZED_TERRACOTTA:
            case Blocks.RED_GLAZED_TERRACOTTA:
            case Blocks.BLACK_GLAZED_TERRACOTTA:
            case Blocks.WHITE_CONCRETE:
            case Blocks.ORANGE_CONCRETE:
            case Blocks.MAGENTA_CONCRETE:
            case Blocks.LIGHT_BLUE_CONCRETE:
            case Blocks.YELLOW_CONCRETE:
            case Blocks.LIME_CONCRETE:
            case Blocks.PINK_CONCRETE:
            case Blocks.GRAY_CONCRETE:
            case Blocks.LIGHT_GRAY_CONCRETE:
            case Blocks.CYAN_CONCRETE:
            case Blocks.PURPLE_CONCRETE:
            case Blocks.BLUE_CONCRETE:
            case Blocks.BROWN_CONCRETE:
            case Blocks.GREEN_CONCRETE:
            case Blocks.RED_CONCRETE:
            case Blocks.BLACK_CONCRETE:
            case Blocks.DRIED_KELP_BLOCK:
            case Blocks.DEAD_TUBE_CORAL_BLOCK:
            case Blocks.DEAD_BRAIN_CORAL_BLOCK:
            case Blocks.DEAD_BUBBLE_CORAL_BLOCK:
            case Blocks.DEAD_FIRE_CORAL_BLOCK:
            case Blocks.DEAD_HORN_CORAL_BLOCK:
            case Blocks.TUBE_CORAL_BLOCK:
            case Blocks.BRAIN_CORAL_BLOCK:
            case Blocks.BUBBLE_CORAL_BLOCK:
            case Blocks.FIRE_CORAL_BLOCK:
            case Blocks.HORN_CORAL_BLOCK:
            case Blocks.BLUE_ICE:
            case Blocks.CONDUIT:
            case Blocks.BUBBLE_COLUMN:
            case Blocks.POLISHED_GRANITE_STAIRS:
            case Blocks.SMOOTH_RED_SANDSTONE_STAIRS:
            case Blocks.MOSSY_STONE_BRICK_STAIRS:
            case Blocks.POLISHED_DIORITE_STAIRS:
            case Blocks.MOSSY_COBBLESTONE_STAIRS:
            case Blocks.END_STONE_BRICK_STAIRS:
            case Blocks.STONE_STAIRS:
            case Blocks.SMOOTH_SANDSTONE_STAIRS:
            case Blocks.SMOOTH_QUARTZ_STAIRS:
            case Blocks.GRANITE_STAIRS:
            case Blocks.ANDESITE_STAIRS:
            case Blocks.RED_NETHER_BRICK_STAIRS:
            case Blocks.POLISHED_ANDESITE_STAIRS:
            case Blocks.DIORITE_STAIRS:
            case Blocks.BRICK_WALL:
            case Blocks.PRISMARINE_WALL:
            case Blocks.RED_SANDSTONE_WALL:
            case Blocks.MOSSY_STONE_BRICK_WALL:
            case Blocks.GRANITE_WALL:
            case Blocks.STONE_BRICK_WALL:
            case Blocks.MUD_BRICK_WALL:
            case Blocks.NETHER_BRICK_WALL:
            case Blocks.ANDESITE_WALL:
            case Blocks.RED_NETHER_BRICK_WALL:
            case Blocks.SANDSTONE_WALL:
            case Blocks.END_STONE_BRICK_WALL:
            case Blocks.DIORITE_WALL:
            case Blocks.SCAFFOLDING:
            case Blocks.LOOM:
            case Blocks.BARREL:
            case Blocks.SMOKER:
            case Blocks.BLAST_FURNACE:
            case Blocks.CARTOGRAPHY_TABLE:
            case Blocks.FLETCHING_TABLE:
            case Blocks.GRINDSTONE:
            case Blocks.LECTERN:
            case Blocks.SMITHING_TABLE:
            case Blocks.STONECUTTER:
            case Blocks.BELL:
            case Blocks.LANTERN:
            case Blocks.SOUL_LANTERN:
            case Blocks.CAMPFIRE:
            case Blocks.SOUL_CAMPFIRE:
            case Blocks.WARPED_STEM:
            case Blocks.STRIPPED_WARPED_STEM:
            case Blocks.WARPED_HYPHAE:
            case Blocks.STRIPPED_WARPED_HYPHAE:
            case Blocks.WARPED_NYLIUM:
            case Blocks.WARPED_FUNGUS:
            case Blocks.WARPED_WART_BLOCK:
            case Blocks.WARPED_ROOTS:
            case Blocks.NETHER_SPROUTS:
            case Blocks.CRIMSON_STEM:
            case Blocks.STRIPPED_CRIMSON_STEM:
            case Blocks.CRIMSON_HYPHAE:
            case Blocks.STRIPPED_CRIMSON_HYPHAE:
            case Blocks.CRIMSON_NYLIUM:
            case Blocks.CRIMSON_FUNGUS:
            case Blocks.SHROOMLIGHT:
            case Blocks.CRIMSON_ROOTS:
            case Blocks.CRIMSON_PLANKS:
            case Blocks.WARPED_PLANKS:
            case Blocks.CRIMSON_STAIRS:
            case Blocks.WARPED_STAIRS:
            case Blocks.CRIMSON_BUTTON:
            case Blocks.WARPED_BUTTON:
            case Blocks.STRUCTURE_BLOCK:
            case Blocks.JIGSAW:
            case Blocks.COMPOSTER:
            case Blocks.TARGET:
            case Blocks.BEE_NEST:
            case Blocks.BEEHIVE:
            case Blocks.HONEY_BLOCK:
            case Blocks.HONEYCOMB_BLOCK:
            case Blocks.NETHERITE_BLOCK:
            case Blocks.ANCIENT_DEBRIS:
            case Blocks.CRYING_OBSIDIAN:
            case Blocks.RESPAWN_ANCHOR:
            case Blocks.LODESTONE:
            case Blocks.BLACKSTONE:
            case Blocks.BLACKSTONE_STAIRS:
            case Blocks.BLACKSTONE_WALL:
            case Blocks.POLISHED_BLACKSTONE:
            case Blocks.POLISHED_BLACKSTONE_BRICKS:
            case Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS:
            case Blocks.CHISELED_POLISHED_BLACKSTONE:
            case Blocks.POLISHED_BLACKSTONE_BRICK_STAIRS:
            case Blocks.POLISHED_BLACKSTONE_BRICK_WALL:
            case Blocks.GILDED_BLACKSTONE:
            case Blocks.POLISHED_BLACKSTONE_STAIRS:
            case Blocks.POLISHED_BLACKSTONE_BUTTON:
            case Blocks.POLISHED_BLACKSTONE_WALL:
            case Blocks.CHISELED_NETHER_BRICKS:
            case Blocks.CRACKED_NETHER_BRICKS:
            case Blocks.QUARTZ_BRICKS:
            case Blocks.AMETHYST_BLOCK:
            case Blocks.BUDDING_AMETHYST:
            case Blocks.AMETHYST_CLUSTER:
            case Blocks.LARGE_AMETHYST_BUD:
            case Blocks.MEDIUM_AMETHYST_BUD:
            case Blocks.SMALL_AMETHYST_BUD:
            case Blocks.TUFF:
            case Blocks.CALCITE:
            case Blocks.TINTED_GLASS:
            case Blocks.SCULK_SENSOR:
            case Blocks.SCULK:
            case Blocks.SCULK_VEIN:
            case Blocks.SCULK_CATALYST:
            case Blocks.SCULK_SHRIEKER:
            case Blocks.OXIDIZED_COPPER:
            case Blocks.WEATHERED_COPPER:
            case Blocks.EXPOSED_COPPER:
            case Blocks.COPPER_BLOCK:
            case Blocks.COPPER_ORE:
            case Blocks.DEEPSLATE_COPPER_ORE:
            case Blocks.OXIDIZED_CUT_COPPER:
            case Blocks.WEATHERED_CUT_COPPER:
            case Blocks.EXPOSED_CUT_COPPER:
            case Blocks.CUT_COPPER:
            case Blocks.OXIDIZED_CUT_COPPER_STAIRS:
            case Blocks.WEATHERED_CUT_COPPER_STAIRS:
            case Blocks.EXPOSED_CUT_COPPER_STAIRS:
            case Blocks.CUT_COPPER_STAIRS:
            case Blocks.WAXED_COPPER_BLOCK:
            case Blocks.WAXED_WEATHERED_COPPER:
            case Blocks.WAXED_EXPOSED_COPPER:
            case Blocks.WAXED_OXIDIZED_COPPER:
            case Blocks.WAXED_OXIDIZED_CUT_COPPER:
            case Blocks.WAXED_WEATHERED_CUT_COPPER:
            case Blocks.WAXED_EXPOSED_CUT_COPPER:
            case Blocks.WAXED_CUT_COPPER:
            case Blocks.WAXED_OXIDIZED_CUT_COPPER_STAIRS:
            case Blocks.WAXED_WEATHERED_CUT_COPPER_STAIRS:
            case Blocks.WAXED_EXPOSED_CUT_COPPER_STAIRS:
            case Blocks.WAXED_CUT_COPPER_STAIRS:
            case Blocks.SPORE_BLOSSOM:
            case Blocks.AZALEA:
            case Blocks.FLOWERING_AZALEA:
            case Blocks.MOSS_BLOCK:
            case Blocks.BIG_DRIPLEAF:
            case Blocks.BIG_DRIPLEAF_STEM:
            case Blocks.SMALL_DRIPLEAF:
            case Blocks.HANGING_ROOTS:
            case Blocks.ROOTED_DIRT:
            case Blocks.MUD:
            case Blocks.DEEPSLATE:
            case Blocks.COBBLED_DEEPSLATE:
            case Blocks.COBBLED_DEEPSLATE_STAIRS:
            case Blocks.COBBLED_DEEPSLATE_WALL:
            case Blocks.POLISHED_DEEPSLATE:
            case Blocks.POLISHED_DEEPSLATE_STAIRS:
            case Blocks.POLISHED_DEEPSLATE_WALL:
            case Blocks.DEEPSLATE_TILES:
            case Blocks.DEEPSLATE_TILE_STAIRS:
            case Blocks.DEEPSLATE_TILE_WALL:
            case Blocks.DEEPSLATE_BRICKS:
            case Blocks.DEEPSLATE_BRICK_STAIRS:
            case Blocks.DEEPSLATE_BRICK_WALL:
            case Blocks.CHISELED_DEEPSLATE:
            case Blocks.CRACKED_DEEPSLATE_BRICKS:
            case Blocks.CRACKED_DEEPSLATE_TILES:
            case Blocks.INFESTED_DEEPSLATE:
            case Blocks.SMOOTH_BASALT:
            case Blocks.RAW_IRON_BLOCK:
            case Blocks.RAW_COPPER_BLOCK:
            case Blocks.RAW_GOLD_BLOCK:
            case Blocks.OCHRE_FROGLIGHT:
            case Blocks.VERDANT_FROGLIGHT:
            case Blocks.PEARLESCENT_FROGLIGHT:
            case Blocks.FROGSPAWN:
            case Blocks.REINFORCED_DEEPSLATE:
            return true;
            default:
            return false;
        }

    }
 */
