# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    tags: 
       - "v*"
    
jobs:   
  build:
   runs-on: ubuntu-latest
   
   steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build


  tagged-release: 
        name: "Preview Release"
        runs-on: "ubuntu-latest"
        steps:
            - name: "Build & test"
              run: |
               echo "done!"

            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: true
                automatic_release_tag: preview
                files: |
                 LICENSE.txt
                 *.jar
